### ISSUE TITLE
Cycle Web or Cycle DOM?

### ISSUE THREAD

**Issue by staltz** [cyclejs/cycle-dom#22]
Supposing this package will remain as a container for virtual DOM, hyperscript, DOM Driver, and HTML Driver (which is basically a replacement for the DOM Driver in server-side rendering use cases), do you think renaming this to "*Cycle DOM*" would be worth it?

Cast your votes.
- Keep Cycle Web
- Rename to Cycle DOM

**Comment by jessep** [comment]
+1

**Comment by jessep** [comment]
To clarify: +1 for the change. Seems like it clarifies the scope of the
package.

**Comment by erykpiast** [comment]
Cycle DOM.

**Comment by Cmdv** [comment]
Cycle DOM feels more intuitive as a name :+1:

**Comment by staltz** [comment]
To me, that's enough votes from credible people. :+1:

**Comment by cgeorg** [comment]
+1 Cycle DOM. There is a lot of other "web" stuff not included.

**Comment by killercup** [comment]
I'm generally in favor of "Cycle DOM", because it's less generic than "web".

I could be not specific enough, though: What would happen if there was an alternative DOM driver? E.g., one based on React's virtual DOM or on Google's incremental-dom?

My point: This package could also be renamed to _cycle-virtual-dom_ to reflect which module it is using under the hood. (Just a thought, I don't think it's actually necessary at this point.)

**Comment by staltz** [comment]
Renamed. https://github.com/cyclejs/cycle-dom/releases/tag/v3.0.0

**Comment by erykpiast** [comment]
:+1:
