### ISSUE TITLE
"Modifying" VirtualNode from `props.children`

### ISSUE THREAD

**Issue by Frikki** [cyclejs/cycle-dom#36]
Given a _custom-element_, when iterating its _children (VirtualNodes)_, I want to prepend a class name, say `my-css-class`, to `VirtualNode.properties.className`.

I understand we should treat all objects, etc., as immutable, so how do I go about this?

```javascript
const modChildren$ = Rx.Observable.from(children)
  .map((vnode) => {
    // How do I prepend the class name of vnode.properties.className when it’s immutable?
  });
```

Also, when I have `modChildren$`, how do I get the stream back to an array again that I can assign to a variable to use in other contexts than within the `subscribe` method?

**Comment by staltz** [comment]
Please make question such as "how do I... ?" in the gitter chat.

Otherwise I think your problem can be solved by not converting back and forth from array to observable and to array. Just use children.map(vnode => ...); And use Object.assign() to make a new object based on the old vnode, and some new properties.

**Comment by Frikki** [comment]
Okay, I will use gitter chat in the future for these questions. Thanks.
