### ISSUE TITLE
Custom elements warn about deprecated function `get`

### ISSUE THREAD

**Issue by ivan-kleshnin** [cyclejs/cycle-dom#38]
https://github.com/cyclejs/cycle-dom/blob/8e62f6aa824b7f5232867a7c684a4b60c2abb01a/src/custom-element-widget.js#L173

This line raises `WARNING: the DOM Driver's get(selector, eventType) is deprecated. Use select(selector).events(eventType) instead.`

**Comment by staltz** [comment]
Thanks, I'll change that and launch a patch version, but custom elements will be deprecated soon as well. I'll release migration guides of course.

**Comment by staltz** [comment]
Done in v5.1.2

**Comment by ivan-kleshnin** [comment]
> Custom elements will be deprecated soon as well. 

Are they going to be replaced with nested dialogues? I took a shallow look at the last and didn't notice significant conceptual difference. May be wrong, of course.

**Comment by staltz** [comment]
>Are they going to be replaced with nested dialogues? 

Yes.

There is very little difference in the implementation of a component, that's good because if you have a function for a custom element, it will be basically the same as a dialogue. But there is a large difference in how you use a component. Custom elements are embedded in the vtree. Nested dialogues are called inside a `main()` (which is a dialogue).
