### ISSUE TITLE
Custom Element cannot set it's own properties and thus cannot completely maintain it's own state.

### ISSUE THREAD

**Issue by alexgig** [cyclejs/cycle-dom#44]
Hello All,

A custom element can read its properties from the `props` driver but cannot write to it's properties via the `props` driver. This prevents a custom element from being able to maintain it's own state completely.

This is most notably an issue when creating custom elements that accept an input value and thus have a `value` property that should be linked to an internal state `value`.

In order to resolve this, the custom element `props` driver would need to be implemented as a source+sink driver.

Consider the following illustration: http://codepen.io/anon/pen/EVKVaW

The "Emit New State" button emits a new state with an incremented `version` and an unchanged `value`. The emission of a new state triggers the emission of a new vtree generated from that state. We expect this new vtree to render all of the input elements using the latest state `value`.

Now do the following:
1. Change the value of "Standard Input".
2. Change the value of "Custom Input".
3. Click the "Emit New State" button.

We see that the "Standard Input" changes as expected. This is because the elements `value` property is changed as the internal value of the element is changed. Thus, when vdom checks to see if the element needs modification, it sees that the element's `value` property no longer equals the latest state `value` and thus re-renders it.

However, we see that the "Custom Input" is not changed as expected. This is because eventhough the internal `value` of the element has changed, its `value` property has not changed. As a result, vdom sees that the element's `value` property still equals the latest state `value` and thus does not modify the element.

If the `props` driver was a source+sink driver, then the following pattern could be used to resolve this issue:

```js
var customInputElement = function (drivers) {
    // ...
    var internalValue = Observable.merge(
      drivers.props.get('value'),
      // ...
    );
    // ...
    return {
        // ...
        props : { value: internalValue }
        // ...
    }
}
```

Thank you and best regards,
Alex

**Comment by staltz** [comment]
Hi Alex,

Everything in Cycle.js is read-only. Everything is reactive. So instead of setting (the correct word here is **mutating**) the properties, you create a new Observable of some state which uses/reads from props and uses its data to make new data. This can be done by mapping the props.get('value') Observable or doing combineLatest with another Observable, or withLatestFrom, etc.

Check an example here: https://github.com/staltz/rxmarbles/blob/master/src/components/diagram-completion.js#L54-L56

I'm certain a custom element **can** maintain it's own state. It is simply the way of achieving this which is in stark contrast with imperative programming where we typically mutate anything we wish.

If you have more questions, I'm sure the community in the gitter chat can help you https://gitter.im/cyclejs/cycle-core

Best regards

**Comment by alexgig** [comment]
Hi André,

Thank you for the quick and thoughtful response. Please allow me to rephrase:

In short:
An HTML `<input/>` element updates its `value` property as it's internal value is changed. As far as I'm aware, it is not possible for a Cycle Custom Element to update its own value property when it's internal value changes. If the `props` driver were both a source _and_ a sink, then a Custom Element could use that driver to do so.

In more detail:
In the above [pen](http://codepen.io/anon/pen/EVKVaW), we create a Cycle Custom Element using vdom and set its `value` property as follows: `h('custom-input', {value: 'Initial'})`.

Then, as you mentioned, we reference the `value` property Observable via `props.get('value')` and merge it with the input event Observable to create an `internalValue` Observable.

What we're missing is a way for a Custom Element to affect it's own `value` property when its internal value changes.

If the `props` driver was a source _and_ a sink, we could return the `internalValue` Observable to the props driver as follows:

```
var customElement = function (drivers) {
    // ...
    var internalValue = Observable.merge(
      drivers.props.get('value'),
      drivers.dom.select('input').events('input').map(e => e.target.value)
    );
    // ...
    return {
        // ...
        props : { value: internalValue }
        // ...
    }
}
```

Then as `internalValue` emits, the `value` property would be updated accordingly by the `props` driver, and the exposed state of the Custom Element (value visible on screen + elements value property) would be consistent.

I hope that is a little clearer. Please let me know if you have any questions or if I've just missed something fundamental here.

Thanks again and best regards,
Alex

**Comment by staltz** [comment]
Why can't you just export a custom event?

```js
var customElement = function (drivers) {
    // ...
    return {
        // ...
        events : { value: internalValue }
        // ...
    }
}
```

Then use it like this

```js
const value$ = DOM.select('custom-input.foo').events('value');
```

**Comment by alexgig** [comment]
Ya, that's best alternative I've come across and it solves the problem of keeping the custom elements internal value and property value in sync BUT it relies on something like main or a parent element to do so which is the issue I'd like to address (ideally the custom element keeps itself consistent).

For instance, the custom element would do the following:

- read value from props -> emit internal value when changed -> emit change event

Then something like main or a parent element would do the following:

- listen for event on custom element -> emit new main/parent internal value when event emitted -> emit new vtree with custom element property set to new value

That last step, when a new vtree is emitted by main, is when the custom element becomes consistent again (internal value = property value). This solution works but requires a knowing and willing third party like main or a parent element to maintain the custom element's exposed state.

A `props` sink driver would enable the custom element to maintain it's own external state and remove the need for the third party.

**Comment by staltz** [comment]
Ok, I see what you are trying to do. You want a [*controlled*](http://facebook.github.io/react/docs/forms.html#controlled-components) custom element. The `props` of custom elements are not designed to support this because their purpose is to represent *inputs* to the custom element, **not** the dynamic state of that custom element. Dynamic state is handled internally to the custom element. If the parent needs to provide new inputs to the custom element, then it's sufficient that the parent gives **new** props to the custom element. "New" here means the value must be distinct to the previous given value. You can also provide the distinctness criteria yourself in the custom element:

[`props.get(propName, comparer)`](https://github.com/cyclejs/cycle-dom/blob/master/src/custom-element-widget.js#L71) is a rather undocumented feature, but you can affect **when** properties by customizing the `comparer` function. For instance the comparer as the function `() => false` would consider every re-render of the parent vtree as a new injection of that property into the custom element.

I know what you are aiming for: parity with the DOM's API for `value` in `<input value="">`. I don't think that is a good DOM API to take inspiration from.

All this said, I also recommend not relying on the custom element API since they'll be soon deprecated for [Nested Dialogues](http://staltz.com/unidirectional-user-interface-architectures.html). There is plenty of effort being put into this direction, which is looking promising and solid.

If you want to still use the custom element API, I recommend not using props as if they would directly represent state. Props are inputs, `events` are output, and active state should be internal to custom elements.

**Comment by alexgig** [comment]
Hi André,

The [Nested Dialogues](http://staltz.com/unidirectional-user-interface-architectures.html) article is actually what lead me to Cycle. Really nice job with both the article and the Cycle documentation! I found them quite insightful, well presented, and inspirational.

Thanks for the heads up on the fact that the custom element API will be deprecated soon. I appreciate you taking the time to understand what I was trying to present in this thread and appreciate the thoughtful feedback.

I'm looking forward to the implementation of Nested Dialogues.

Thank you again and best regards,
Alex
