### ISSUE TITLE
Allow `.events` to take an array so as to observe multiple events

### ISSUE THREAD

**Issue by ckknight** [cyclejs/cycle-dom#46]
The API I'm proposing would allow for the `.events` method to take an array of strings as well as just a string (as is the current API):

The following
```js
return DOM.select('a').events(['click', 'touchstart', 'touchdown']);
```

should be roughly equivalent to
```js
const eventTypes = ['click', 'touchstart', 'touchdown'];
const selection = DOM.select('a');
return Rx.Observable.merge(eventTypes.map(e => selection.events(e)));
```

**Comment by HighOnDrive** [comment]
Great idea, was always interested in using what is called "event shortcuts" here: https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/events.md

**Comment by TylorS** [comment]
:+1:

**Comment by staltz** [comment]
Sorry, I won't take this proposal because it **adds API to Cycle where it would be enough to just use RxJS API**. I want Cycle to be a small complement to RxJS, not a contendent. People who know RxJS should be able to pick up Cycle.js as if it had almost nothing else than just RxJS.

This
```js
const a = DOM.select('a');
return a.events('click').merge(a.events('touchstart')).merge(a.events('touchdown'));
```
or this
```js
return Rx.Observable.merge(
  DOM.select('a').events('click'),
  DOM.select('a').events('touchstart'),
  DOM.select('a').events('touchdown')
);
```
are not that bad alternatives.

If you want the helper function, just make it as some utils and use it in your codebase.

**Comment by marton78** [comment]
Alternatively, you could accept an array in `events` and output an array.

This would enable the following:

```js
return Rx.Observable.merge.apply(Rx.Observable, DOM.select('a').events(['click', 'touchstart', 'touchdown']));
```

**Comment by arlair** [comment]
Thanks. I found this useful as a person learning RxJS and Cycle.js. Initially I was thinking events in plural form meant I could pass more than one and had to dig into the code to see what was happening.
