### ISSUE TITLE
Global or local selectors

### ISSUE THREAD

**Issue by nickdima** [cyclejs/cycle-dom#60]
From the documentation is not clear if the `select` function queries the whole DOM or just the subtree rendered by a component.

**Comment by Frikki** [comment]
At the moment, `select(selector)` uses `querySelectorAll()` from the root element.

**Comment by nickdima** [comment]
Would you consider bad practice subscribing to events on elements outside of the rendered subtree?

**Comment by Frikki** [comment]
No. For example, in UI designs, it is quite common that an ancestor wants to know whether a descendant received or lost focus. Since neither bubbles, you can use `useCapture` to catch the event as it trickles down. A different approach, however, would be to return the state of a descendant component, which would indicate whether it is focused or not. A parent can read the state of a child, and a child receives props from the parent.

**Comment by nickdima** [comment]
@Frikki
>  A parent can read the state of a child, and a child receives props from the parent.

What if the components are too "distant" from each other, wouldn't this process become tedious in a large app? Is there an alternative?
